# Generated by Django 5.1.1 on 2024-09-28 12:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('profile_path', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='release_date')),
                ('orig_title', models.CharField(max_length=100, unique_for_date='release_date')),
                ('status', models.CharField(choices=[('ANNOUNCED', 'Announced'), ('PRE-PRODUCTION', 'Pre-production'), ('FILMING', 'Filming'), ('POST-PRODUCTION', 'Post-production'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released')], max_length=15)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.PositiveIntegerField(blank=True, default=0)),
                ('budget', models.PositiveIntegerField(blank=True, default=0)),
                ('runtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=100)),
                ('overview', models.TextField(blank=True, default='')),
                ('poster_path', models.CharField(blank=True, default='', max_length=32)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=32)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('prod_companies', models.ManyToManyField(to='movies.company')),
                ('prod_countries', models.ManyToManyField(to='movies.country')),
                ('spoken_langs', models.ManyToManyField(to='movies.language')),
                ('cast', models.ManyToManyField(related_name='cast', to='movies.person')),
                ('cinematographer', models.ManyToManyField(related_name='cinematographer', to='movies.person')),
                ('composer', models.ManyToManyField(related_name='composer', to='movies.person')),
                ('director', models.ManyToManyField(related_name='director', to='movies.person')),
                ('producer', models.ManyToManyField(related_name='producer', to='movies.person')),
                ('writer', models.ManyToManyField(related_name='writer', to='movies.person')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
