# Generated by Django 5.1.1 on 2024-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_ratings_average_movie_ratings_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
