# Generated by Django 5.1.1 on 2024-10-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='orig_title',
            field=models.CharField(max_length=200, unique_for_date='release_date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, unique_for_date='release_date'),
        ),
    ]
