# Generated by Django 5.1.1 on 2024-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_company_name_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
