# Generated by Django 5.1.1 on 2024-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_recommend_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bayesian_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
